try{}
catch(Exception e) {
  <begin>print e<end>
}
-----
try{}
catch(Exception e) {
    testMethod(e)
}

private def testMethod(Exception e) {
    print e
}