try {
  foo();
}
catch (e: java.lang.Exception) {
  bar();
}
finally {
  return;
}